export default {
  '0e384e19': [() => import(/* webpackChunkName: '0e384e19' */ '@site/docs/intro.md'), '@site/docs/intro.md', require.resolveWeak('@site/docs/intro.md')],
  '17896441': [() => import(/* webpackChunkName: '17896441' */ '@theme/DocItem'), '@theme/DocItem', require.resolveWeak('@theme/DocItem')],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ '@theme/DocPage'), '@theme/DocPage', require.resolveWeak('@theme/DocPage')],
  '1f391b9e': [() => import(/* webpackChunkName: '1f391b9e' */ '@theme/MDXPage'), '@theme/MDXPage', require.resolveWeak('@theme/MDXPage')],
  '20f5f7f3': [() => import(/* webpackChunkName: '20f5f7f3' */ '@site/docs/protocol.md'), '@site/docs/protocol.md', require.resolveWeak('@site/docs/protocol.md')],
  '393be207': [() => import(/* webpackChunkName: '393be207' */ '@site/src/pages/markdown-page.md'), '@site/src/pages/markdown-page.md', require.resolveWeak('@site/src/pages/markdown-page.md')],
  '5bd90cbb': [() => import(/* webpackChunkName: '5bd90cbb' */ '/Users/robertgawdzik/src/protocol/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json'), '/Users/robertgawdzik/src/protocol/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json', require.resolveWeak('/Users/robertgawdzik/src/protocol/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json')],
  '5e9f5e1a': [() => import(/* webpackChunkName: '5e9f5e1a' */ '@generated/docusaurus.config'), '@generated/docusaurus.config', require.resolveWeak('@generated/docusaurus.config')],
  '761bfdf5': [() => import(/* webpackChunkName: '761bfdf5' */ '@site/docs/data.md'), '@site/docs/data.md', require.resolveWeak('@site/docs/data.md')],
  '85be18e3': [() => import(/* webpackChunkName: '85be18e3' */ '@site/docs/conclusion.md'), '@site/docs/conclusion.md', require.resolveWeak('@site/docs/conclusion.md')],
  '8b083a83': [() => import(/* webpackChunkName: '8b083a83' */ '@site/docs/nft.md'), '@site/docs/nft.md', require.resolveWeak('@site/docs/nft.md')],
  '935f2afb': [() => import(/* webpackChunkName: '935f2afb' */ '~docs/default/version-current-metadata-prop-751.json'), '~docs/default/version-current-metadata-prop-751.json', require.resolveWeak('~docs/default/version-current-metadata-prop-751.json')],
  'bae0b67c': [() => import(/* webpackChunkName: 'bae0b67c' */ '/Users/robertgawdzik/src/protocol/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json'), '/Users/robertgawdzik/src/protocol/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json', require.resolveWeak('/Users/robertgawdzik/src/protocol/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json')],
  'c4f5d8e4': [() => import(/* webpackChunkName: 'c4f5d8e4' */ '@site/src/pages/index.js'), '@site/src/pages/index.js', require.resolveWeak('@site/src/pages/index.js')],};
